#!/usr/bin/env node

/**
 * Build Script: Generate promptData.generated.js from JSON prompt files
 *
 * This script reads all JSON files from config/prompts/, validates them,
 * and generates an ES module that can be imported by promptManager.js.
 * This approach works with Cloudflare Workers which cannot read files at runtime.
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const PROMPTS_DIR = path.join(__dirname, '..', 'config', 'prompts');
const OUTPUT_PATH = path.join(__dirname, '..', 'utils', 'promptData.generated.js');
const REQUIRED_FIELDS = ['id', 'name', 'description', 'systemPrompt'];

console.log('🔨 Building promptData.generated.js from config/prompts/*.json\n');

// Read all JSON files (sorted for deterministic output)
const files = fs.readdirSync(PROMPTS_DIR)
  .filter(f => f.endsWith('.json') && f !== '.backup')
  .sort();

if (files.length === 0) {
  console.error('❌ No JSON files found in config/prompts/');
  process.exit(1);
}

console.log(`Found ${files.length} prompt files\n`);

const bundle = {};
const hash = crypto.createHash('sha256');

for (const file of files) {
  const fullPath = path.join(PROMPTS_DIR, file);
  const relPath = `./config/prompts/${file}`;
  let data;

  // Parse JSON - fail hard on errors
  try {
    const content = fs.readFileSync(fullPath, 'utf8');
    data = JSON.parse(content);
  } catch (err) {
    console.error(`❌ Failed to parse ${file}: ${err.message}`);
    process.exit(1);
  }

  // Validate required fields
  const missingFields = REQUIRED_FIELDS.filter(field => !data[field]);
  if (missingFields.length > 0) {
    console.error(`❌ Invalid prompt ${file}: missing required fields: ${missingFields.join(', ')}`);
    process.exit(1);
  }

  bundle[relPath] = data;
  hash.update(JSON.stringify(data));
  console.log(`  ✓ ${file} (${data.id})`);
}

// Generate output
const serialized = JSON.stringify(bundle, null, 2);
const timestamp = new Date().toISOString();
const sourceHash = hash.digest('hex').slice(0, 7);

const output = `// Auto-generated by scripts/build-prompts.js on ${timestamp}
// Source hash: ${sourceHash}
// Do not edit by hand. Edit the JSON files in config/prompts/ and run: npm run build
export const promptConfigs = ${serialized};
`;

// Write output file
fs.writeFileSync(OUTPUT_PATH, output, 'utf8');

const sizeKB = (Buffer.byteLength(output) / 1024).toFixed(1);
console.log(`\n✅ Successfully generated utils/promptData.generated.js`);
console.log(`📦 File size: ${sizeKB} KB (${files.length} prompts)`);
console.log(`🔑 Source hash: ${sourceHash}`);
